SELECT YEAR(SALES_DATE) AS YEAR
     , MONTH(SALES_DATE) AS MONTH
     , USER.GENDER AS GENDER
     , COUNT(DISTINCT ONLINE.USER_ID) AS USERS
  FROM ONLINE_SALE ONLINE
  LEFT OUTER JOIN USER_INFO USER ON (USER.USER_ID = ONLINE.USER_ID)
 WHERE USER.GENDER IS NOT NULL
 GROUP BY YEAR(SALES_DATE)
        , MONTH(SALES_DATE)
        , USER.GENDER
 ORDER BY YEAR(SALES_DATE)
        , MONTH(SALES_DATE)
        , USER.GENDER;