WITH TOTAL_SALE AS (
    SELECT SALES_DATE
         , PRODUCT_ID
         , USER_ID
         , SALES_AMOUNT
      FROM ONLINE_SALE
     UNION ALL
    SELECT SALES_DATE
         , PRODUCT_ID
         , NULL AS USER_ID
         , SALES_AMOUNT
      FROM OFFLINE_SALE
)
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
     , PRODUCT_ID
     , USER_ID
     , SALES_AMOUNT
  FROM TOTAL_SALE
 WHERE SALES_DATE BETWEEN '2022-03-01' AND '2022-03-31'
 ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;