WITH TOTAL_USERS AS (
    SELECT COUNT(USER_ID) AS TOTAL
      FROM USER_INFO
     WHERE YEAR(JOINED) = '2021'
)
SELECT YEAR(ONLINE.SALES_DATE) AS YEAR
     , MONTH(ONLINE.SALES_DATE) AS MONTH
     , COUNT(DISTINCT ONLINE.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT ONLINE.USER_ID) / (SELECT TOTAL FROM TOTAL_USERS), 1) AS PUCHASED_RATIO
  FROM ONLINE_SALE ONLINE
 INNER JOIN USER_INFO USER ON (USER.USER_ID = ONLINE.USER_ID)
 WHERE YEAR(USER.JOINED) = '2021'
 GROUP BY YEAR(ONLINE.SALES_DATE), MONTH(ONLINE.SALES_DATE)
 ORDER BY YEAR(ONLINE.SALES_DATE), MONTH(ONLINE.SALES_DATE);