-- 코드를 입력하세요
SELECT INS.ANIMAL_ID
     , INS.ANIMAL_TYPE
     , INS.NAME
  FROM ANIMAL_INS INS
  LEFT OUTER JOIN ANIMAL_OUTS OUTS ON (INS.ANIMAL_ID = OUTS.ANIMAL_ID)
 WHERE INS.SEX_UPON_INTAKE <> OUTS.SEX_UPON_OUTCOME
   AND OUTS.ANIMAL_ID IS NOT NULL