WITH RECURSIVE GENERATIONS AS (
    SELECT THE_FIRST.ID
         , THE_FIRST.PARENT_ID
         , 1 AS GENERATION
      FROM ECOLI_DATA AS THE_FIRST
     WHERE THE_FIRST.PARENT_ID IS NULL
     UNION ALL
    SELECT CHILD.ID
         , CHILD.PARENT_ID
         , PARENT.GENERATION + 1 AS GENERATION
      FROM ECOLI_DATA AS CHILD
     INNER JOIN GENERATIONS AS PARENT ON CHILD.PARENT_ID = PARENT.ID
) 
SELECT COUNT(GENERATION) AS COUNT
     , GENERATION
  FROM GENERATIONS 
 WHERE NOT EXISTS (
    SELECT ID
      FROM ECOLI_DATA 
     WHERE ECOLI_DATA .PARENT_ID = GENERATIONS.ID
 )
 GROUP BY GENERATION