SELECT PROD.PRODUCT_CODE
     , SUM(PROD.PRICE) * SUM_AMOUNT AS SALES
  FROM PRODUCT PROD
  LEFT OUTER JOIN ( SELECT PRODUCT_ID
                         , SUM(SALES_AMOUNT) AS SUM_AMOUNT
                      FROM OFFLINE_SALE
                     GROUP BY PRODUCT_ID) OFFLINE ON (OFFLINE.PRODUCT_ID = PROD.PRODUCT_ID)
 WHERE OFFLINE.PRODUCT_ID IS NOT NULL
 GROUP BY PROD.PRODUCT_CODE
 ORDER BY SUM(PROD.PRICE) * SUM_AMOUNT DESC, PROD.PRODUCT_CODE;