SELECT PROD.PRODUCT_ID
     , PROD.PRODUCT_NAME
     , SUM(PROD.PRICE) * ODR.AMOUNT AS TOTAL_SALES
  FROM FOOD_PRODUCT PROD
 INNER JOIN ( SELECT DATE_FORMAT(PRODUCE_DATE, '%Y%m') AS YM
                         , PRODUCT_ID
                         , SUM(AMOUNT) AS AMOUNT
                      FROM FOOD_ORDER
                     WHERE DATE_FORMAT(PRODUCE_DATE, '%Y%m') = '202205'
                     GROUP BY DATE_FORMAT(PRODUCE_DATE, '%Y%m'), PRODUCT_ID ) ODR ON (ODR.PRODUCT_ID = PROD.PRODUCT_ID)
 GROUP BY ODR.YM, PROD.PRODUCT_ID
 ORDER BY SUM(PROD.PRICE) * ODR.AMOUNT DESC, PROD.PRODUCT_ID;