-- 코드를 입력하세요
SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR
     , COUNT(DATE_FORMAT(DATETIME, '%H')) AS COUNT
  FROM ANIMAL_OUTS
 WHERE DATE_FORMAT(DATETIME, '%H%I%S') BETWEEN '0900' AND '1959'
 GROUP BY DATE_FORMAT(DATETIME, '%H')
 ORDER BY DATE_FORMAT(DATETIME, '%H');