SELECT APP.APNT_NO
     , PAT.PT_NAME
     , APP.PT_NO
     , APP.MCDP_CD
     , DOC.DR_NAME
     , APP.APNT_YMD
  FROM APPOINTMENT APP
 INNER JOIN PATIENT PAT ON (PAT.PT_NO = APP.PT_NO)
 INNER JOIN DOCTOR DOC ON (DOC.DR_ID = APP.MDDR_ID AND DOC.MCDP_CD = APP.MCDP_CD)
 WHERE COALESCE(APP.APNT_CNCL_YN, 'N') <> 'Y'
   AND APP.MCDP_CD = 'CS'
   AND DATE_FORMAT(APP.APNT_YMD, '%Y%m%d') = '20220413'
 ORDER BY APP.APNT_YMD;