WITH AVERAGE_REST_REVIEW AS (
    SELECT REST_ID
         , ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
      FROM REST_REVIEW
     GROUP BY REST_ID
)
SELECT REST.REST_ID
     , REST.REST_NAME
     , REST.FOOD_TYPE
     , REST.FAVORITES
     , REST.ADDRESS
     , REVIEW.SCORE
  FROM REST_INFO REST
  LEFT OUTER JOIN AVERAGE_REST_REVIEW REVIEW ON (REVIEW.REST_ID = REST.REST_ID)
 WHERE REVIEW.REST_ID IS NOT NULL
   AND REST.ADDRESS LIKE '서울%'
 ORDER BY REVIEW.SCORE DESC, REST.FAVORITES DESC;